import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { NavBar } from "~/components/NavBar";
import { Session } from "inspector";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "~/provider/authProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} bg-gray-200/50`}>
          <NavBar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
